# Generated by Django 5.2.12 on 2026-05-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sellersettlement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospectactivity',
            options={'ordering': ['-activity_date', '-created_at']},
        ),
    ]
