# Generated by Django 5.2.12 on 2026-05-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_prospectactivity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectclient',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
