# Generated by Django 5.2.12 on 2026-03-17 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=24)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('primary_language', models.CharField(choices=[('en', 'English'), ('pl', 'Polski')], default='pl', max_length=2)),
                ('short_description_en', models.CharField(blank=True, max_length=280)),
                ('short_description_pl', models.CharField(blank=True, max_length=280)),
                ('long_description_en', models.TextField(blank=True)),
                ('long_description_pl', models.TextField(blank=True)),
                ('public', models.BooleanField(default=True)),
                ('allow_ai_indexing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('update', 'Update'), ('faq', 'FAQ'), ('guide', 'Guide'), ('case-study', 'Case study')], default='update', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary_en', models.CharField(blank=True, max_length=280)),
                ('summary_pl', models.CharField(blank=True, max_length=280)),
                ('content_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_entries', to='companies.organization')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description_en', models.CharField(blank=True, max_length=280)),
                ('short_description_pl', models.CharField(blank=True, max_length=280)),
                ('product_url', models.URLField(blank=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.organization')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=32)),
                ('url', models.URLField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to='companies.organization')),
            ],
            options={
                'ordering': ['network'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('pl', 'Polski')], max_length=2)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='companies.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='companies_o_slug_846ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['public', 'allow_ai_indexing'], name='companies_o_public_1a7a0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'network'), name='unique_network_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'language'), name='unique_tag_per_language'),
        ),
    ]
