# Generated by Django 5.2.12 on 2026-03-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='content_languages',
            field=models.JSONField(default=list, help_text='Selected content languages for this organization'),
        ),
    ]
