# Generated by Django 5.2.12 on 2026-04-17 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='source_type',
            field=models.CharField(choices=[('user_submitted', 'User submitted')], default='user_submitted', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('human_admin_verified', 'Human admin verified')], default='unverified', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
