# Generated by Django 5.2.12 on 2026-04-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_organization_source_type_organization_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
