# Generated by Django 5.2.12 on 2026-05-27 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PLUS', 'Plus'), ('PRO', 'Pro')], max_length=16)),
                ('stripe_price_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in the smallest currency unit, e.g. grosz/cents.')),
                ('currency', models.CharField(default='pln', max_length=8)),
                ('interval', models.CharField(choices=[('year', 'Year')], default='year', max_length=16)),
                ('active_for_new_customers', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tier', '-active_for_new_customers', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PLUS', 'Plus'), ('PRO', 'Pro')], max_length=16)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='incomplete', max_length=32)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('latest_invoice_id', models.CharField(blank=True, max_length=255)),
                ('latest_payment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.billingplanprice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='pln', max_length=8)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('open', 'Open'), ('void', 'Void'), ('uncollectible', 'Uncollectible'), ('failed', 'Failed')], default='open', max_length=32)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('hosted_invoice_url', models.URLField(blank=True)),
                ('invoice_pdf', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.billingsubscription')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingplanprice',
            constraint=models.UniqueConstraint(condition=models.Q(('active_for_new_customers', True)), fields=('tier',), name='one_active_billing_price_per_tier'),
        ),
    ]
