# Generated by Django 5.2.12 on 2026-06-18 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billingsubscription_stripe_subscription_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingplanprice',
            options={'ordering': ['tier', 'currency', '-active_for_new_customers', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='billingplanprice',
            name='one_active_billing_price_per_tier',
        ),
        migrations.AlterField(
            model_name='billingplanprice',
            name='currency',
            field=models.CharField(choices=[('pln', 'PLN'), ('eur', 'EUR')], default='pln', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='billingplanprice',
            constraint=models.UniqueConstraint(condition=models.Q(('active_for_new_customers', True)), fields=('tier', 'currency'), name='one_active_billing_price_per_tier_currency'),
        ),
    ]
