# Generated by Django 5.2.12 on 2026-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='tax_id',
            field=models.CharField(max_length=64),
        ),
    ]
