from django.urls import path

from .views import (
    ClientChangeSellerView,
    ClientDetailView,
    ClientListView,
    ClientVerifyView,
    CustomerInvoiceDownloadView,
    CustomerInvoiceListView,
    BillingOverviewView,
    BillingInvoiceAdminDownloadView,
    BillingInvoiceCreateView,
    BillingPaymentInvoiceUpdateView,
    BillingPortalView,
    BillingPriceActivateView,
    BillingPriceUpdateView,
    BillingProfileView,
    BillingSubscriptionCancelView,
    BillingSubscriptionReactivateView,
    BillingPriceArchiveView,
    BillingPriceManagementView,
    DashboardHomeView,
    OrganizationReviewView,
    OrganizationVerifyView,
    PlanCheckoutCancelView,
    PlanCheckoutSuccessView,
    OrganizationCreateView,
    OrganizationDeleteView,
    OrganizationUpdateView,
    PlanUpdateView,
    ProspectActivityAddView,
    ProspectCreateView,
    ProspectDetailView,
    ProspectLinkClientView,
    ProspectUpdateView,
    SellerActivityReportView,
    SellerAccessToggleView,
    SellerClientsListView,
    SellerDeleteView,
    SellerDetailView,
    SellerListView,
    SellerSettlementCreateView,
    SellerSettlementListView,
    SellerProspectsListView,
)


app_name = "dashboard"

urlpatterns = [
    path("", DashboardHomeView.as_view(), name="home"),
    path("plan/", PlanUpdateView.as_view(), name="plan-update"),
    path("plan/billing-profile/", BillingProfileView.as_view(), name="billing-profile"),
    path("plan/invoices/", CustomerInvoiceListView.as_view(), name="customer-invoices"),
    path("plan/invoices/<int:pk>/download/", CustomerInvoiceDownloadView.as_view(), name="customer-invoice-download"),
    path("plan/billing-portal/", BillingPortalView.as_view(), name="billing-portal"),
    path("plan/subscription/cancel/", BillingSubscriptionCancelView.as_view(), name="billing-subscription-cancel"),
    path("plan/subscription/reactivate/", BillingSubscriptionReactivateView.as_view(), name="billing-subscription-reactivate"),
    path("plan/checkout/success/", PlanCheckoutSuccessView.as_view(), name="plan-checkout-success"),
    path("plan/checkout/cancel/", PlanCheckoutCancelView.as_view(), name="plan-checkout-cancel"),
    path("organizations/new/", OrganizationCreateView.as_view(), name="organization-create"),
    path("organizations/<int:pk>/edit/", OrganizationUpdateView.as_view(), name="organization-edit"),
    path("organizations/<int:pk>/delete/", OrganizationDeleteView.as_view(), name="organization-delete"),
    path("organizations/<int:pk>/review/", OrganizationReviewView.as_view(), name="organization-review"),
    path("organizations/<int:pk>/verify/", OrganizationVerifyView.as_view(), name="organization-verify"),
    path("clients/", ClientListView.as_view(), name="client-list"),
    path("billing/prices/", BillingPriceManagementView.as_view(), name="billing-price-management"),
    path("billing/prices/<int:pk>/edit/", BillingPriceUpdateView.as_view(), name="billing-price-edit"),
    path("billing/prices/<int:pk>/activate/", BillingPriceActivateView.as_view(), name="billing-price-activate"),
    path("billing/prices/<int:pk>/archive/", BillingPriceArchiveView.as_view(), name="billing-price-archive"),
    path("billing/overview/", BillingOverviewView.as_view(), name="billing-overview"),
    path("billing/subscriptions/<int:subscription_pk>/invoices/add/", BillingInvoiceCreateView.as_view(), name="billing-invoice-add"),
    path("billing/payments/<int:pk>/invoice/", BillingPaymentInvoiceUpdateView.as_view(), name="billing-payment-invoice-update"),
    path("billing/payments/<int:pk>/invoice/download/", BillingInvoiceAdminDownloadView.as_view(), name="billing-invoice-admin-download"),
    path("clients/<int:pk>/verify/", ClientVerifyView.as_view(), name="client-verify"),
    path("clients/<int:pk>/change-seller/", ClientChangeSellerView.as_view(), name="client-change-seller"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client-detail"),
    path("sellers/", SellerListView.as_view(), name="seller-list"),
    path("reports/seller-activities/", SellerActivityReportView.as_view(), name="report-seller-activities"),
    path("sellers/settlements/", SellerSettlementListView.as_view(), name="seller-settlements"),
    path("sellers/settlements/<int:prospect_pk>/settle/", SellerSettlementCreateView.as_view(), name="seller-settlement-create"),
    path("sellers/<int:pk>/", SellerDetailView.as_view(), name="seller-detail"),
    path("sellers/<int:pk>/toggle-access/", SellerAccessToggleView.as_view(), name="seller-toggle-access"),
    path("sellers/<int:pk>/delete/", SellerDeleteView.as_view(), name="seller-delete"),
    # Seller workspace routes
    path("seller/clients/", SellerClientsListView.as_view(), name="seller-clients"),
    path("seller/prospects/", SellerProspectsListView.as_view(), name="seller-prospects"),
    path("seller/prospects/new/", ProspectCreateView.as_view(), name="prospect-create"),
    path("seller/prospects/<int:pk>/edit/", ProspectUpdateView.as_view(), name="prospect-edit"),
    path("seller/prospects/<int:pk>/", ProspectDetailView.as_view(), name="prospect-detail"),
    path("seller/prospects/<int:pk>/link-client/", ProspectLinkClientView.as_view(), name="prospect-link-client"),
    path("seller/prospects/<int:prospect_pk>/activity/", ProspectActivityAddView.as_view(), name="prospect-activity-add"),
]

