# Generated by Django 5.2.12 on 2026-07-08 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('customer', 'Customer'), ('plan', 'Plan'), ('payment', 'Payment'), ('invoice', 'Invoice'), ('manual_plan', 'Pro Manual'), ('stripe', 'Stripe')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('urgent', 'Urgent')], default='info', max_length=16)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('reference_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['closed_at', '-created_at'],
                'indexes': [models.Index(fields=['closed_at', '-created_at'], name='notificatio_closed__86ea00_idx'), models.Index(fields=['category', 'closed_at'], name='notificatio_categor_92973f_idx'), models.Index(fields=['severity', 'closed_at'], name='notificatio_severit_95071c_idx')],
            },
        ),
    ]
