# Generated by Django 5.2.12 on 2026-07-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_customernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='message_pl',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='title_pl',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='message_pl',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='title_pl',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
